### PR TITLE
Adding support for Symfony4

### PR DESCRIPTION
**Pull request by larzuk91**
Attempt to add support for Symfony4

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Tests on Symfony 4 are broken :/

**Comment by kbond** [comment]
Thanks @larzuk91, I've fixed some issues with the tests and adjusted the travis config. Hopefully that will get travis green and I can merge and tag.

**Comment by larzuk91** [comment]
Hey, @kbond thanks for the support :)
There is a failure on your last commit: `- phpunit/phpunit 5.7.0 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].`
Probably you have to upgrade phpunit with its dependencies?

**Comment by kbond** [comment]
It is a bug with composer: https://github.com/composer/composer/issues/5355 - I'm applying a work-around.

**Comment by larzuk91** [comment]
Ohh that's interesting, I wasn't aware of that bug
Look like it worked! Nice job man.

**Comment by kbond** [comment]
Great! I am just pushing one more change to require php 5.6+ and I will release 3.1 shortly.

**Comment by larzuk91** [comment]
Awesome! Thank you very much for your support

**Comment by larzuk91** [comment]
It works, confirmed - I just upgraded and ran all my tests

**Comment by kbond** [comment]
Excellent!

**Pull request merged**
